#! /bin/sh

cd /usr/share/copr/coprs_frontend/
./manage.py create-db --alembic alembic.ini
./manage.py create-chroot $(ls /etc/mock/openeuler-*-{i386,x86_64}.cfg |xargs -I{} -n1 basename {} .cfg)
exec /usr/sbin/httpd -DFOREGROUND


