#!/bin/python3
import os
import sys
import logging
import ecs_servers

log_file = "/home/resalloc/provision/create-x86.log"  # 修改为你的日志文件路径
logging.basicConfig(filename=log_file, level=logging.INFO)
logger = logging.getLogger('local-new-x86')

name = os.getenv('RESALLOC_NAME')
if name is None:
    print('RESALLOC_NAME not set')
    sys.exit(1)

e = ecs_servers.ECSServers(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'ecs_servers.yaml'))
res = e.create_servers('x86', 'l1', e.name_prefix + name)
if res['code'] != 200:
    print(res['error'])
    sys.exit(1)
else:
    if len(res['server_ips']) != 1:
        print('create servers failed, more than one server ip returned')
        sys.exit(1)
    else:
        print(res['server_ips'][0])
        sys.exit(0)