#!/bin/bash
namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
if [ -z $namespace ];then
    exit 1
fi
/resalloc-kubernetes add --image-tag pkking/copr_builder@${BUILDER_SHA256} \
    --namespace $namespace --cpu-resource 500m --memory-resource 769Mi --privileged --timeout 120 --node-selector "os.architecture=amd64" --node-selector "usage=test"
