#!/bin/bash
namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
if [ -z $namespace ];then
    exit 1
fi
/resalloc-kubernetes add --image-tag pkking/copr_builder@sha256:59514663018cd2e03d65cf44abecfdb5b2b8450453afd3700d733f2581b23566 \
    --namespace $namespace --cpu-resource 500m --memory-resource 769Mi --privileged --timeout 120 --node-selector "os.architecture=aarch64" --node-selector "usage=test"
