apiVersion: apps/v1
kind: Deployment
metadata:
  name: copr-distgit
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: copr-distgit
  template:
    metadata:
      labels:
        component: copr-distgit
    spec:
      nodeSelector:
        usage: test
        os.architecture: amd64
      initContainers:
        - name: init-distgit
          image: busybox:1.28
          command: [ "sh", "-c", "until nslookup copr-frontend.fedora-copr.svc.cluster.local; do echo waiting for frontend service ; sleep 2; done;" ]
      containers:
        - image: pkking/copr_distgit@sha256:069bc9c2af013ece024cfa17f333b125eec36cf75d33a09cefd8736303f0020c
          imagePullPolicy: IfNotPresent
          name: copr-distgit-httpd
          livenessProbe:
            tcpSocket:
              port: 5001
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 5001
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 5001
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/dist-git
              name: copr-distgit-data
            - mountPath: /var/lib/copr-dist-git
              name: logs
          command: ["/usr/sbin/httpd", "-DFOREGROUND"]
        - image: pkking/copr_distgit@sha256:069bc9c2af013ece024cfa17f333b125eec36cf75d33a09cefd8736303f0020c
          imagePullPolicy: IfNotPresent
          name: copr-distgit
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - mountPath: /var/lib/dist-git
              name: copr-distgit-data
            - mountPath: /etc/copr/copr-dist-git.conf
              name: copr-secrets
              subPath: distgit_copr-dist-git.conf
            - name: logs
              mountPath: /var/lib/copr-dist-git
            - name: locks
              mountPath: /var/lock/copr-dist-git
      volumes:
        - name: copr-distgit-data
          persistentVolumeClaim:
            claimName: copr-distgit-data
        - name: copr-distgit
          configMap:
            name: copr-distgit
        - name: logs
          persistentVolumeClaim:
            claimName: copr-distgit-logs
        - name: locks
          persistentVolumeClaim:
            claimName: copr-distgit-locks
        - name: copr-secrets
          secret:
            secretName: copr-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: copr-distgit
spec:
  ports:
    - name: httpd
      port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    component: copr-distgit
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copr-distgit-data
  labels:
    failure-domain.beta.kubernetes.io/zone: cn-north-4a
  annotations:
    everest.io/disk-volume-type: SSD
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copr-distgit-logs
  labels:
    failure-domain.beta.kubernetes.io/zone: cn-north-4a
  annotations:
    everest.io/disk-volume-type: SSD
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copr-distgit-locks
  labels:
    failure-domain.beta.kubernetes.io/zone: cn-north-4a
  annotations:
    everest.io/disk-volume-type: SSD
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10M"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: distgit-cronjob-month
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - copr-distgit
                topologyKey: kubernetes.io/hostname
          containers:
          - image: pkking/copr_distgit@sha256:069bc9c2af013ece024cfa17f333b125eec36cf75d33a09cefd8736303f0020c
            name: distgit-cronjob
            args: ["sudo", "/etc/cron.monthly/copr-dist-git"]
            volumeMounts:
              - mountPath: /var/lib/dist-git
                name: copr-distgit-data
              - mountPath: /etc/copr/copr-dist-git.conf
                name: copr-secrets
                subPath: distgit_copr-dist-git.conf
              - name: logs
                mountPath: /var/lib/copr-dist-git
              - name: locks
                mountPath: /var/lock/copr-dist-git
          volumes:
            - name: copr-distgit-data
              persistentVolumeClaim:
                claimName: copr-distgit-data
            - name: copr-distgit
              configMap:
                name: copr-distgit
            - name: logs
              persistentVolumeClaim:
                claimName: copr-distgit-logs
            - name: locks
              persistentVolumeClaim:
                claimName: copr-distgit-locks
            - name: copr-secrets
              secret:
                secretName: copr-secrets
          restartPolicy: OnFailure