apiVersion: apps/v1
kind: Deployment
metadata:
  name: copr-keygen
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: copr-keygen
  template:
    metadata:
      labels:
        component: copr-keygen
    spec:
      nodeSelector:
        usage: test
        os.architecture: amd64
      containers:
        - image: pkking/copr_keygen-signd@sha256:9394b8562ac46b4d4da3b701598dd00011e2f556cd7aadae4564caa141eee59f
          imagePullPolicy: IfNotPresent
          args: ["/signd-entrypoint", "0.0.0.0/0"]
          name: copr-keygen-signer
          livenessProbe:
            tcpSocket:
              port: 5167
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 5167
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 5167
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/copr-keygen
              name: copr-keygen-data
        - image: pkking/copr_keygen-signd@sha256:9394b8562ac46b4d4da3b701598dd00011e2f556cd7aadae4564caa141eee59f
          imagePullPolicy: IfNotPresent
          name: copr-keygen-httpd
          livenessProbe:
            tcpSocket:
              port: 5003
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: 5003
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 5003
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/copr-keygen
              name: copr-keygen-data
            - mountPath: /etc/httpd/conf.d/copr-keygen.conf
              name: copr-keygen
              subPath: copr-keygen.conf
      volumes:
        - name: copr-keygen-data
          persistentVolumeClaim:
            claimName: copr-keygen-data
        - name: copr-keygen
          configMap:
            name: copr-keygen

---
apiVersion: v1
kind: Service
metadata:
  name: copr-keygen
spec:
  ports:
    - name: httpd
      port: 5003
      protocol: TCP
      targetPort: 5003
    - name: signer
      port: 5167
      protocol: TCP
      targetPort: 5167
  selector:
    component: copr-keygen
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copr-keygen-data
  labels:
    failure-domain.beta.kubernetes.io/zone: cn-north-4a
  annotations:
    everest.io/disk-volume-type: SSD
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: keygen-cronjob-daily
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - copr-keygen
                topologyKey: kubernetes.io/hostname
          containers:
          - image: pkking/copr_keygen-signd@sha256:9394b8562ac46b4d4da3b701598dd00011e2f556cd7aadae4564caa141eee59f
            name: keygen-cronjob
            args: ["sudo", "/etc/cron.daily/copr-keygen"]
            volumeMounts:
              - mountPath: /var/lib/copr-keygen
                name: copr-keygen-data
              - mountPath: /etc/httpd/conf.d/copr-keygen.conf
                name: copr-keygen
                subPath: copr-keygen.conf
          volumes:
            - name: copr-keygen-data
              persistentVolumeClaim:
                claimName: copr-keygen-data
            - name: copr-keygen
              configMap:
                name: copr-keygen
          restartPolicy: OnFailure