resources:
- namespace.yaml
- database.yaml
- redis.yaml
- frontend.yaml
- keygen.yaml
- distgit.yaml
- resalloc.yaml
- backend.yaml
- ingress.yaml
- secrets.yaml
commonLabels:
  app: copr
configMapGenerator:
- files:
  - initdb.sh=config/database/initdb.sh
  name: copr-database
- files:
  - httpd.conf=config/frontend/httpd.conf
  name: copr-frontend
- files:
  - copr-keygen.conf=config/keygen/copr-keygen.conf
  name: copr-keygen
- files:
  - pools.yaml=config/resalloc/pools.yaml
  - builder_config=config/backend/.ssh/builder_config
  - local-new-aarch64=config/resalloc/local-new-aarch64
  - local-new-x86=config/resalloc/local-new-x86
  name: copr-resalloc
- files:
  - builder_config=config/backend/.ssh/builder_config
  name: copr-backend
namespace: fedora-copr
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# database image
# redis image
# resalloc image
# distgit image
# keygen image
# frontend image
# builder image
# backend image
images:
- digest: sha256:5f9cb57fd1690dab535b59c897e8eedb931f0c366a26314f96161456dfe641c4
  name: pkking/copr_backend
- digest: sha256:81726fbc6ca39f6d7591f4d17a8f650451dc0f79c87d966c4b453c9c31931121
  name: pkking/copr_backend_httpd
- digest: sha256:60ebf96a23be8edbc0d59404de3dafff5cb8c00602cea7fe1ffecb73ad09867e
  name: pkking/copr_database
- digest: sha256:88b083eb05130e7b506af249605f94e7ea8c8bd856bf9376d68e5b35fb036b30
  name: pkking/copr_distgit
- digest: sha256:9321c088f2df0fddbad9cc728fb0c754d7c60ec9548846d49cf6f9b35db0d0a2
  name: pkking/copr_frontend
- digest: sha256:4dafeff3e84cc983b6be388a2a5a61b41ff2cdfd0259013efd7dc9f2348be9b3
  name: pkking/copr_keygen-signd
- digest: sha256:90e29dc00ca0806b32bf391af43bc9058053b3cef4763182fd4e30d6371a83e9
  name: pkking/copr_resalloc
