resources:
- namespace.yaml
- database.yaml
- redis.yaml
- frontend.yaml
- keygen.yaml
- distgit.yaml
- resalloc.yaml
- backend.yaml
- ingress.yaml
- secrets.yaml
commonLabels:
  app: copr
configMapGenerator:
- files:
  - initdb.sh=config/database/initdb.sh
  name: copr-database
- files:
  - httpd.conf=config/frontend/httpd.conf
  name: copr-frontend
- files:
  - copr-keygen.conf=config/keygen/copr-keygen.conf
  name: copr-keygen
- files:
  - pools.yaml=config/resalloc/pools.yaml
  - builder_config=config/backend/.ssh/builder_config
  - local-new-aarch64=config/resalloc/local-new-aarch64
  - local-new-x86=config/resalloc/local-new-x86
  name: copr-resalloc
- files:
  - builder_config=config/backend/.ssh/builder_config
  name: copr-backend
namespace: fedora-copr
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# database image
# redis image
# resalloc image
# distgit image
# keygen image
# frontend image
# builder image
# backend image
images:
- digest: sha256:b3b653b955b38a9bb5011b9356e5c61a0439df3dce5fffe50b683bcd9c001498
  name: pkking/copr_backend
- digest: sha256:02e94e9b8d60d7d60bb6ca0c3e882856342b733af9d6fd5f9c364d621ecc5d4d
  name: pkking/copr_backend_httpd
- digest: sha256:c0065ed893be9e851cf058b39bfbe89a1d7e36b02cf52b61ce5b29751e9c2de5
  name: pkking/copr_database
- digest: sha256:4c08ec5307695b75cc7d4f9b2492bd28508c539ee39d942802db1185aae97b78
  name: pkking/copr_distgit
- digest: sha256:193a4ba78e3703bb56d33a89c3ede24e3f45f15ad4f400b67f608b39b113d19e
  name: pkking/copr_frontend
- digest: sha256:9cefeb590c76d8dec3fd6f80fcb07e522ceb520c8d7adc2bdb6163ee786d21c7
  name: pkking/copr_keygen-signd
- digest: sha256:f77d84c56f056fb6a401e3a4d21e3786b3df4b5114ecc1f01d4350bde7f31a62
  name: pkking/copr_resalloc
