resources:
- namespace.yaml
- database.yaml
- redis.yaml
- frontend.yaml
- keygen.yaml
- distgit.yaml
- resalloc.yaml
- backend.yaml
- ingress.yaml
- secrets.yaml
commonLabels:
  app: copr
configMapGenerator:
- files:
  - initdb.sh=config/database/initdb.sh
  name: copr-database
- files:
  - httpd.conf=config/frontend/httpd.conf
  name: copr-frontend
- files:
  - copr-keygen.conf=config/keygen/copr-keygen.conf
  name: copr-keygen
- files:
  - pools.yaml=config/resalloc/pools.yaml
  - builder_config=config/backend/.ssh/builder_config
  - local-new-aarch64=config/resalloc/local-new-aarch64
  - local-new-x86=config/resalloc/local-new-x86
  name: copr-resalloc
- files:
  - builder_config=config/backend/.ssh/builder_config
  name: copr-backend
namespace: fedora-copr
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# database image
# redis image
# resalloc image
# distgit image
# keygen image
# frontend image
# builder image
# backend image
images:
- digest: sha256:347ed80dcf6d7ae8383b0e434b78d8ff50fd3e9e8e1179651af9d2a09ab06b2d
  name: pkking/copr_backend
- digest: sha256:81726fbc6ca39f6d7591f4d17a8f650451dc0f79c87d966c4b453c9c31931121
  name: pkking/copr_backend_httpd
- digest: sha256:60ebf96a23be8edbc0d59404de3dafff5cb8c00602cea7fe1ffecb73ad09867e
  name: pkking/copr_database
- digest: sha256:4c08ec5307695b75cc7d4f9b2492bd28508c539ee39d942802db1185aae97b78
  name: pkking/copr_distgit
- digest: sha256:9d4e2a9f284fefb37cdf856b8a800ede214ae036d0c6a9b26c9a294807ac2dc3
  name: pkking/copr_frontend
- digest: sha256:9cefeb590c76d8dec3fd6f80fcb07e522ceb520c8d7adc2bdb6163ee786d21c7
  name: pkking/copr_keygen-signd
- digest: sha256:cf76316c5c506971c82df6c58a635a7eae86efe8acd77376d5873d931e9ef64c
  name: pkking/copr_resalloc
