resources:
- namespace.yaml
- database.yaml
- redis.yaml
- frontend.yaml
- keygen.yaml
- distgit.yaml
- resalloc.yaml
- backend.yaml
- ingress.yaml
- secrets.yaml
commonLabels:
  app: copr
configMapGenerator:
- files:
  - initdb.sh=config/database/initdb.sh
  name: copr-database
- files:
  - httpd.conf=config/frontend/httpd.conf
  name: copr-frontend
- files:
  - copr-keygen.conf=config/keygen/copr-keygen.conf
  name: copr-keygen
- files:
  - pools.yaml=config/resalloc/pools.yaml
  - builder_config=config/backend/.ssh/builder_config
  name: copr-resalloc
- files:
  - builder_config=config/backend/.ssh/builder_config
  name: copr-backend
namespace: fedora-copr
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
# database image
- name: copr_database:latest
  newName: copr_database
  newTag: latest
# redis image
- name: centos/redis-32-centos7
  newName: centos/redis-32-centos7
  newTag: latest
# resalloc image
- name: copr_resalloc:latest
  newName: copr_resalloc
  newTag: latest
# distgit image
- name: copr_distgit-httpd:latest
  newName: copr_distgit-httpd
  newTag: latest
- name: copr_distgit:latest
  newName: copr_distgit
  newTag: latest
# keygen image
- name: copr_keygen-httpd:latest
  newName: copr_keygen-httpd
  newTag: latest
- name: copr_keygen-signd:latest
  newName: copr_keygen-signd
  newTag: latest
# frontend image
- name: copr_frontend:latest
  newName: copr_frontend
  newTag: latest
# builder image
- name: copr_builder:latest
  newName: copr_builder
  newTag: latest
# backend image
- name: copr_backend_httpd:latest
  newName: copr_backend_httpd
  newTag: latest
- name: copr_backend-log:latest
  newName: copr_backend-log
  newTag: latest
- name: copr_backend-action:latest
  newName: copr_backend-action
  newTag: latest
- name: copr_backend-build:latest
  newName: copr_backend-build
  newTag: latest
