#!/bin/bash
/usr/bin/chown copr-dist-git:packager -R /var/lib/dist-git/git
/usr/bin/find /var/lib/dist-git/git -type d -print0 | xargs -0 -n100 sudo chmod 2775
/usr/bin/find /var/lib/dist-git/git -type f -print0 | xargs -0 -n100 sudo chmod 664

chown copr-dist-git:copr-dist-git -R /var/lib/copr-dist-git
find /var/lib/copr-dist-git -type d -print0 | xargs -0 -n100 sudo chmod 775
find /var/lib/copr-dist-git -type f -print0 | xargs -0 -n100 sudo chmod 664

chown copr-dist-git:copr-dist-git -R /var/lib/dist-git/cache/lookaside
find /var/lib/dist-git/cache/lookaside -type d -print0 | xargs -0 -n100 sudo chmod 775
find /var/lib/dist-git/cache/lookaside -type f -print0 | xargs -0 -n100 sudo chmod 664